#!/usr/bin/env python3
"""
Example usage script untuk Jinja2 Template Generator System
Demonstrasi berbagai cara penggunaan template dengan data dari CSV, JSON, dan AI
"""

from template_generator import TemplateGenerator
from sample_data.ai_testimonial_data import get_testimonial_data
import json

def main():
    # Initialize template generator
    generator = TemplateGenerator()
    
    print("🎨 Jinja2 Template Generator System")
    print("=" * 50)
    
    # 1. Generate blog dari CSV
    print("\n1. Generate Blog dari CSV...")
    try:
        csv_data = generator.load_csv_data("sample_data/blog_data.csv")
        if csv_data:
            content = generator.generate_content(
                "blog_grid.html", 
                csv_data, 
                "output/blog_from_csv.html"
            )
            print("✅ Blog grid berhasil di-generate dari CSV")
        else:
            print("❌ Data CSV tidak ditemukan")
    except Exception as e:
        print(f"❌ Error: {e}")
    
    # 2. Generate product catalog dari JSON
    print("\n2. Generate Product Catalog dari JSON...")
    try:
        json_data = generator.load_json_data("sample_data/product_data.json")
        if json_data:
            content = generator.generate_content(
                "product_catalog.html",
                json_data,
                "output/products_from_json.html"
            )
            print("✅ Product catalog berhasil di-generate dari JSON")
        else:
            print("❌ Data JSON tidak ditemukan")
    except Exception as e:
        print(f"❌ Error: {e}")
    
    # 3. Generate testimonials dari AI data
    print("\n3. Generate Testimonials dari AI Data...")
    try:
        ai_data = get_testimonial_data()
        processed_ai_data = generator.load_ai_data(ai_data)
        content = generator.generate_content(
            "testimonial_carousel.html",
            processed_ai_data,
            "output/testimonials_from_ai.html"
        )
        print("✅ Testimonials berhasil di-generate dari AI data")
    except Exception as e:
        print(f"❌ Error: {e}")
    
    # 4. Generate multiple templates dengan batch processing
    print("\n4. Batch Generation...")
    try:
        data_sources = [
            {
                "type": "csv",
                "path": "sample_data/blog_data.csv",
                "output": "batch_blog.html"
            },
            {
                "type": "json", 
                "path": "sample_data/product_data.json",
                "output": "batch_products.html"
            },
            {
                "type": "ai",
                "data": get_testimonial_data(),
                "output": "batch_testimonials.html"
            }
        ]
        
        # Generate dengan template yang berbeda
        generator.batch_generate("news_magazine.html", data_sources[:1], "output/news")
        generator.batch_generate("portfolio_gallery.html", data_sources[1:2], "output/portfolio") 
        generator.batch_generate("event_calendar.html", data_sources[2:], "output/events")
        
        print("✅ Batch generation selesai")
    except Exception as e:
        print(f"❌ Error batch: {e}")
    
    # 5. Demo semua template dengan data sample
    print("\n5. Generate Demo untuk Semua Template...")
    templates = generator.list_templates()
    
    # Sample data untuk demo
    demo_data = {
        "title": "Demo Content",
        "subtitle": "Generated by Jinja2 Template System",
        "items": [
            {
                "title": "Sample Item 1",
                "description": "Ini adalah contoh item untuk demo template",
                "image": "https://via.placeholder.com/400x300",
                "category": "Demo",
                "author": "Template Generator",
                "date": "2024-12-01",
                "url": "#"
            },
            {
                "title": "Sample Item 2", 
                "description": "Item kedua untuk menunjukkan variasi template",
                "image": "https://via.placeholder.com/400x300",
                "category": "Example",
                "author": "AI System",
                "date": "2024-12-01",
                "url": "#"
            }
        ]
    }
    
    for template in templates:
        try:
            template_name = template.replace('.html', '')
            output_file = f"output/demo_{template_name}.html"
            generator.generate_content(template, demo_data, output_file)
            print(f"✅ Demo generated: {template}")
        except Exception as e:
            print(f"❌ Error dengan {template}: {e}")
    
    print(f"\n🎉 Selesai! Total template tersedia: {len(templates)}")
    print(f"📁 Hasil dapat dilihat di folder 'output/'")
    print("\n📋 Template yang tersedia:")
    for i, template in enumerate(templates, 1):
        print(f"   {i}. {template}")

if __name__ == "__main__":
    main()